// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-TS2nvNK1MKlvNHmmg1BHfmieswXev4',
    appId: '1:467733816131:web:8218232110adefc22245f6',
    messagingSenderId: '467733816131',
    projectId: 'dictionary-2876e',
    authDomain: 'dictionary-2876e.firebaseapp.com',
    storageBucket: 'dictionary-2876e.appspot.com',
    measurementId: 'G-D20GW9D300',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUK9J5uBE0r47MHKpG0mStx04hVwiT4s',
    appId: '1:467733816131:android:f024379a176305822245f6',
    messagingSenderId: '467733816131',
    projectId: 'dictionary-2876e',
    storageBucket: 'dictionary-2876e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkt6SxB4TeFMx9WifGYMQIA5qDn6CmT4g',
    appId: '1:467733816131:ios:ce9304b84a771fd42245f6',
    messagingSenderId: '467733816131',
    projectId: 'dictionary-2876e',
    storageBucket: 'dictionary-2876e.appspot.com',
    iosBundleId: 'com.lincolncaetano.dictionary.dictionary',
  );
}
